/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import imagen.ImageClass;
import java.awt.image.BufferedImage;

/**
 *
 * @author MAURI
 */
public class Brillo_Contraste extends javax.swing.JFrame {

    ImageClass bc;
    
    /**
     * Creates new form Brillo_Contraste
     */
    public Brillo_Contraste(BufferedImage img) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderBrillo = new javax.swing.JSlider();
        sliderContraste = new javax.swing.JSlider();
        labelBrillo = new javax.swing.JLabel();
        labelContraste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brillo y Contraste");
        setMinimumSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(null);
        getContentPane().add(sliderBrillo);
        sliderBrillo.setBounds(20, 30, 280, 16);
        getContentPane().add(sliderContraste);
        sliderContraste.setBounds(20, 100, 280, 16);

        labelBrillo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBrillo.setText("Brillo");
        getContentPane().add(labelBrillo);
        labelBrillo.setBounds(300, 30, 50, 19);

        labelContraste.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelContraste.setText("Contraste");
        getContentPane().add(labelContraste);
        labelContraste.setBounds(300, 100, 70, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brillo_Contraste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brillo_Contraste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brillo_Contraste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brillo_Contraste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Brillo_Contraste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBrillo;
    private javax.swing.JLabel labelContraste;
    private javax.swing.JSlider sliderBrillo;
    private javax.swing.JSlider sliderContraste;
    // End of variables declaration//GEN-END:variables
}
